server:
  port: 8080

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false

  profiles:
    active: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true