version: "3"
services:
  kafka:
    image: 'bitnami/kafka:3.5.1'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=CONTROLLER://:9093,PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.2.34:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@:9093
      - ALLOW_PLAINTEXT_LISTENER=yes

  secdb:
    image: 'postgis/postgis:15-3.4'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: 3
    volumes:
      - /home/rseals/var/lib/postgres/data/secdb:/var/lib/postgresql/data

  pgadmin:
    image: 'dpage/pgadmin4:7.6'
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    logging:
      options:
        max-size: 10m
        max-file: 3
    volumes:
      - /home/rseals/var/lib/pgadmin:/var/lib/pgadmin